version: 2

models:

  - name: fct_orders
    columns:

      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_id

      - name: product_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_id
