version: 2

models:

  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

      - name: email
        tests:
          - not_null

  - name: dim_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
