name: dbt-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      - name: Setup dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          ecommerce_dbt:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: dummy
                user: dummy
                password: dummy
                role: dummy
                database: dummy
                warehouse: dummy
                schema: dummy
          EOF

      - name: Compile dbt (SAFE MODE)
        run: |
          cd ecommerce_dbt
          dbt parse
